# Generated by Django 2.1.2 on 2018-10-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('discourse_url', models.URLField(max_length=120, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('introduction', models.TextField(max_length=1000)),
                ('position', models.CharField(choices=[('intern', 'INTERN'), ('software developer', 'SOFTWARE DEVELOPER'), ('founder', 'FOUNDER')], default='Intern', max_length=30)),
                ('start_date', models.DateField(max_length=120)),
                ('finish_date', models.DateField(max_length=120)),
                ('picture_upload', models.ImageField(max_length=120, upload_to='')),
                ('work_done', models.CharField(max_length=120)),
            ],
        ),
    ]
