# Generated by Django 2.1.2 on 2018-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181029_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='interns',
            name='fav_experience',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
