# Generated by Django 2.1.2 on 2018-11-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20181030_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interns',
            options={'ordering': ['-finish_date']},
        ),
    ]
