# Generated by Django 2.1.2 on 2018-11-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('pages', '0007_auto_20181104_0703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interns',
            new_name='intern',
        ),
    ]
