# Generated by Django 2.1.2 on 2018-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, unique=True)),
                ('short_name', models.CharField(max_length=120, unique=True)),
                ('url_id', models.URLField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=30)),
                ('official_link', models.URLField(max_length=120, unique=True)),
                ('logo_picture', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('established_date', models.DateField()),
            ],
            options={
                'ordering': ['-established_date'],
            },
        ),
    ]
