# Generated by Django 2.1.2 on 2018-11-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='url_id',
        ),
    ]
