# Generated by Django 2.1.2 on 2018-11-06 05:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20181106_1033'),
    ]

    