# Generated by Django 2.1.2 on 2018-11-08 05:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20181106_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
