# Generated by Django 2.1.2 on 2018-11-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20181108_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='abc',
        ),
    ]
