# Generated by Django 2.1.2 on 2018-11-08 11:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_remove_school_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='descqription1',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
