# Generated by Django 2.1.2 on 2018-11-08 11:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20181108_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='descqription1',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
