# Generated by Django 2.1.2 on 2018-11-08 12:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20181108_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='descqription1',
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
