# Generated by Django 2.1.2 on 2018-12-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20181108_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='opengenus_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
