# Generated by Django 2.1.2 on 2018-12-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_school_opengenus_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='opengenus_rating',
            field=models.FloatField(default=0),
        ),
    ]
